"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const billing_controller_1 = require("../controllers/billing.controller");
const auth_1 = require("../middleware/auth");
const router = (0, express_1.Router)({ mergeParams: true });
router.post('/generate', auth_1.authRequired, billing_controller_1.generateBills);
router.get('/', auth_1.authRequired, billing_controller_1.getBills);
router.get('/overdue', auth_1.authRequired, billing_controller_1.getOverdueBills);
router.get('/:billId', auth_1.authRequired, billing_controller_1.getBillById);
router.get('/:billId/receipt', auth_1.authRequired, billing_controller_1.getReceipt);
router.post('/:billId/payments', auth_1.authRequired, billing_controller_1.recordPayment);
exports.default = router;
