-- The "amenities" and "pg_amenities" tables are now created earlier in
-- migration 20260531062000_create_amenities_tables, since the
-- 20260531064843_rename_photo_categories_add_room_amenities migration
-- (which runs before this one) already depends on "amenities" existing.
-- This migration is intentionally a no-op to keep migration history append-only.
